<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="llenadoTanque" Id="{730c9376-bdb9-48a0-bb3c-62f695fd5010}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION llenadoTanque : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="llenadoTanque">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>